apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231101092256.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231101092256.0.0+build.02e9424
  releaseNotes: |
    Release v20231101092256.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-11-2023-04-22-20-599992551/where-for-dinner-search-my-apps-bundle@sha256:0dd996ba7bd4ed7e93774331e5ea2e2926fd2160bacd2afb32bd0809a7972655
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

