apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231101092220.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231101092220.0.0+build.02e9424
  releaseNotes: |
    Release v20231101092220.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-11-2023-04-22-20-599992551/where-for-dinner-my-apps-bundle@sha256:948a00a084f5a28f156ae4543bf23c11ec2114b9eeafeb3d3491a405d98dd420
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

